### PR TITLE
add hover image in person detail page

### PR DESCRIPTION
**Pull request by boney-bun**
fix kartoza/kartoza.com#60

### CODE REVIEW

**Comment by boney-bun** [comment]
@carina1000 something like below?
kartoza com 60

**Comment by carina1000** [comment]
Hey @boney-bun - Not exactly. 
This page should by default show our avatars - but when hovered over our real life image appears
screen shot 2019-02-26 at 08 58 00
screen shot 2019-02-26 at 08 58 10


When you click on the actual person and read their detail (your view above) We should only see their real-life image... As it is here: (NO HOVER OVER ACTIONS AT THIS VIEW)
screen shot 2019-02-26 at 08 58 59

**Comment by boney-bun** [comment]
Hi @carina1000 
i've done a few changes in the production as you wish. 
could you check it out?

**Comment by carina1000** [comment]
Hi @boney-bun very cool - thank you!! Can you just please remove the hover over functionality at this view:
53393421-fb986880-39a4-11e9-989f-8b80199a937c

We just want to see the real-life photo here :) thanks

**Comment by boney-bun** [comment]
@carina1000 done
can i merge and close this issue?

**Comment by carina1000** [comment]
Yes @boney-bun

**Comment by boney-bun** [comment]
thanks @carina1000 
i'm going to merge this PR

**Pull request merged**
