### PR TITLE
added tweeter feeds

### LINKED ISSUE #33: We need to integrate a twitter feed block on the front page
Maybe next to the blog feed block (see #31 ) we can have a twitter feed. We can set it up to show any recent tweets from Gav or me I guess...? Or maybe mentions of Kartoza? What do you think @gubuntu ?

See also http://mezzanine.jupo.org/docs/twitter-integration.html

Note that if we use cron it should run in a separate container. Otherwise consider celery-beat (maybe @lucernae can pick up this ticket if needed as he has used beat a lot). Also please enable twitter posting when publishing a new blog post (also explained in the page above).

### PR DESCRIPTION
**Pull request by meomancer**
@timlinux 

this fix #33 

added tweeter feeds, tested in production env
- add tweeter feeds on landing page
- celery beat to pull twitter for every 10 mins
- send tweeter when post new blog

some screenes:
selection_007
selection_008
selection_009

but, i am not sure why **devweb** can't be deployed

> ssh://root@localhost:64203/usr/local/bin/python -u /home/web/django_project/manage.py runserver 0.0.0.0:8080
> {'PYTHONIOENCODING': 'UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'PYTHONPATH': '/home/meomancer/Development/docker-mezzanine:/home/web/django_project', 'SHLVL': '1', 'SSH_TTY': '/dev/pts/0', 'OLDPWD': '/home/web/django_project', 'JETBRAINS_REMOTE_RUN': '1', 'PWD': '/home/web/django_project', 'PYCHARM_HOSTED': '1', 'SSH_CLIENT': '172.17.0.1 46840 22', 'DJANGO_SETTINGS_MODULE': 'core.settings.dev_docker', 'USER': 'root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'MAIL': '/var/mail/root', 'LOGNAME': 'root', 'SSH_CONNECTION': '172.17.0.1 46840 172.17.0.22 22', 'HOME': '/root', 'PYTHONUNBUFFERED': '1', '_': '/usr/bin/env'}
> Traceback (most recent call last):
>   File "/home/web/django_project/manage.py", line 11, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 303, in execute
>     settings.INSTALLED_APPS
>   File "/usr/local/lib/python2.7/site-packages/django/conf/**init**.py", line 48, in **getattr**
>     self._setup(name)
>   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in **init**
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/local/lib/python2.7/importlib/**init**.py", line 37, in import_module
>     **import**(name)
>   File "/home/web/django_project/core/settings/dev_docker.py", line 6, in <module>
>     from .dev import \*  # noqa
>   File "/home/web/django_project/core/settings/dev.py", line 1, in <module>
>     from .project import \*  # noqa
>   File "/home/web/django_project/core/settings/project.py", line 12, in <module>
>     from .contrib import \*  # noqa
>   File "/home/web/django_project/core/settings/contrib.py", line 216, in <module>
>     BROKER_URL = 'amqp://guest:guest@%s:5672//' % os.environ['RABBITMQ_HOST']
>   File "/usr/local/lib/python2.7/UserDict.py", line 40, in **getitem**
>     raise KeyError(key)
> KeyError: 'RABBITMQ_HOST'

although i already set RABBITMQ_HOST in devweb compose

**Another blocks is** 
- when we post with new blog but straightly as published, it post to twitter but url is unset. Will overide save model to handle it.

### CODE REVIEW

**Comment by gubuntu** [comment]
nice

**Comment by timlinux** [comment]
Are we ready to merge this?

**Comment by meomancer** [comment]
@timlinux 
for production env, it is ready
but for development, it is not
it breaks development and i am not sure why RABBITMQ_HOST is still not found

**Comment by cchristelis** [comment]
@meomancer, please freshen this up and merge.

**Pull request merged**
