### PR TITLE
update invoice layout

### LINKED ISSUE #164: fix order business logic and reports
- [x] add Kartoza logo to order e.g. http://kartoza.com/en/shop/invoice/4/
- [x] Add 'Tax Invoice' to the above order/invoice template. 
- [x] phone numbers should be text fields or formatted with leading 0 
- [x] add supplier details to the order (all Kartoza company details incl VAT no.)
- [ ] fix the order view / model (http://kartoza.com/en/admin/shop/order/4/) because it is incorrect and should match the 'invoice' in the link above. I think it's a tax implementation issue - it should be calculating VAT on the discounted amount. 
- [x] Figure out what Unprocessed/Processed does in Order admin - or is it just a boolean flag?

### PR DESCRIPTION
**Pull request by meomancer**
hi @gubuntu 
this partial fix #164 
is this layout good?
selection_027

note, this layout is broken in pdf, still developing it

### CODE REVIEW

**Comment by gubuntu** [comment]
nice. Kartoza's VAT number needs to be listed under the Kartoza address for it to be a valid tax invoice.

**Comment by meomancer** [comment]
@gubuntu what is kartoza vat's number?

updated phone input using regex (leading by 0)
screenshot from 2016-11-16 14 43 28

**Comment by gubuntu** [comment]
Company no: 2014/109067/07 

VAT Number: 4450266806

**Comment by meomancer** [comment]
@gubuntu 
it seems xhtml2pdf is broken for that layout
- height of table is wrong
- logo is not rendered
  i already search it but still no luck
  selection_028

and i see that xhtml2pdf is abandoned and we are encouraged to use weasy_print
xhtml2pdf is core code from mezzanine, and if we change to weasy_print (doesn't try it yet to see rendering) we have to change mezzanine too

what do you suggest?
my suggest is maybe for now
- disable download pdf, instead just show pdf in browser
- make save button to save it (we could do it in javascript, because browser already give API for that)

**Comment by gubuntu** [comment]
makes sense to use browser API. Then user can download it from browser if they want. 

and create a ticket upstream suggesting mezzanine replace xhtml2pdf with weasy_print

**Comment by meomancer** [comment]
@https://github.com/stephenmcd/mezzanine/issues/1699

**Comment by meomancer** [comment]
https://github.com/stephenmcd/mezzanine/issues/1699

**Comment by meomancer** [comment]
new invoice:

selection_030
selection_031
selection_032
selection_033

**Comment by timlinux** [comment]
Wow that looks really beautiful @meomancer 

I would suggest to remove the dual office entries and just say 'Address' with the stellenbosch address listed.

**Comment by meomancer** [comment]
selection_034

new layout

**Comment by gubuntu** [comment]
yes looks great @meomancer

**Comment by gubuntu** [comment]
please merge and deploy

**Comment by meomancer** [comment]
@gubuntu 
deployed with version 1.2.0
here is example : http://kartoza.com/id/shop/invoice/15/

**Comment by gubuntu** [comment]
thanks @meomancer, good work

**Pull request merged**
