### PR TITLE
added payment

### LINKED ISSUE #114: integrate payment gateway(s)

### PR DESCRIPTION
**Pull request by meomancer**
@gubuntu @cchristelis 
this fix #114 

is it ok for Manual Payment?
User make confirmation and from this data, admin can check to bank and making complete paymen or order on admin site
And also, payment page on checkout is disable due to this method

Note : need to change the account info in https://cloud.githubusercontent.com/assets/4530905/18345605/661b1d9a-75e6-11e6-998b-ee246e17c5d0.png

and also we could put payment confirmation link in navbar?

screenshot from 2016-09-08 16 44 59
screenshot from 2016-09-08 16 45 54
screenshot from 2016-09-08 16 55 42
screenshot from 2016-09-08 16 56 45
screenshot from 2016-09-08 16 56 54

### CODE REVIEW

**Comment by timlinux** [comment]
I don't know if @cchristelis chatted to you about this @meomancer , but for the client payment side, we don't need their bank details. All we need to do is give them an instruction like:

---

Please pay by EFT (Electronic Funds Transfer) to this bank account:

xxxxxx kartoza bank details here

Please use the reference Kartoza-<invoice no> when making the transfer.

---

Replace the <invoice-no> with the actual invoice. Then Petra should be able to go into the backend and confirm the payment is received when we se it in our account, then she can send them a receipt / payment confirmation. Hope that makes sense?

**Comment by gubuntu** [comment]
Almost there

Where can we change the account info and the message in the 'Order complete' page?

For the user to submit proof of payment I think the only fields that are necessary are name and order number (not bank and bank account) and the free text field with a note to paste the pop (if they have it text e.g. html) plus an option to upload a pop (e.g. a scanned pop or a pdf)

Remember this must still work as an option (manual payment) when we start bringing in Paypal, credit cards, etc.

**Comment by meomancer** [comment]
@gubuntu @timlinux 
Updated model:
- removed bank account of user
- added file field to be uploaded

"Remember this must still work as an option (manual payment) when we start bringing in Paypal, credit cards, etc."
Still not implemented yet

**Comment by gubuntu** [comment]
LGTM, please fix conflicts, merge and release by Monday morning

**Comment by meomancer** [comment]
@gubuntu 
merged
for payment information, it can be changed at https://github.com/kartoza/docker-mezzanine/blob/develop/django_project/payment/templates/payment/includes/payment-information.html

**Pull request merged**
