### PR TITLE
add adwords tags

### PR DESCRIPTION
**Pull request by boney-bun**
the conversion is calculated on the completion page, not on wishlish or cart.
revise of the previous commit #217.

fix kartoza/kartoza.com#32

### CODE REVIEW

**Comment by boney-bun** [comment]
i'll merge so we can test on testing

**Comment by gubuntu** [comment]
@boney-bun please test on testing by completing an order and confirming that the Adwords snippet is in the source of the completion page. 

then go ahead and deploy to production before our campaign goes out in 2h from now.

**Comment by boney-bun** [comment]
@gubuntu it's been deployed to the testing server. 
I don't have access to Kartoza's google adwords.
perhaps @carina1000 can help verify it?
i guess there will be logs whenever we try to access the testing.

**Comment by gubuntu** [comment]
you don't need access to Adwords, just inspect the source code of the page you get

**Comment by boney-bun** [comment]
yes, i have tried that.
the conversion js shows up only on a completion page,  while the global tracking always appear in all pages.
what is the expectation for the code @carina1000 ?
one more thing, i've disabled the old adword code.

**Comment by gubuntu** [comment]
I didn't ask you to disable the old code. It is not old Adwords code but Analytics code. Please leave it there. 

Otherwise the behaviour is fine, @carina1000 doesn't need to test. 

Re-enable the analytics code and deploy to production asap.

**Pull request merged**
