### PR TITLE
Added fb integration

### LINKED ISSUE #68: Please add Facebook integration
Includes the following:

- [ ] click on Like / Follow button on our website 
    - https://github.com/shurik/Mezzanine_Facebook
- [ ] Link FB button to our FB page (add our FB link to the FB button in the footer)
- [ ] post blogs to our FB page automatically (see first comment below)

Gav to supply api details for secret.py

### PR DESCRIPTION
**Pull request by rischanlab**
fix #68 
Facebook page like on the home page. 

screen shot 2016-11-02 at 7 13 50 am

### CODE REVIEW

**Comment by boney-bun** [comment]
this is an old PR.
could we close this one @gubuntu ?

**Comment by gubuntu** [comment]
has it already been done in another PR?

**Comment by boney-bun** [comment]
yes, it has in kartoza/kartoza.com#9

**Comment by gubuntu** [comment]
superseded bby https://github.com/kartoza/docker-mezzanine/pull/229

**Pull request closed without merging**
