### PR TITLE
fixing uwsgi zombie container

### LINKED ISSUE #50: uwsgi containers go zombie
Please watch on mountain - it accumulates many uwsgi containers over time - can you look into why and fix? It may relate to the restart=always option in docker-compose.

### PR DESCRIPTION
**Pull request by meomancer**
@timlinux this fix #50 
yes, the zombie container raised because of failed migration

i also fixed failed migration when fresh deployment.

**before** :
screenshot from 2016-08-31 12 37 15

**fixs**
screenshot from 2016-08-31 12 45 11
screenshot from 2016-08-31 12 45 16

### CODE REVIEW

**Comment by dimasciput** [comment]
@meomancer would it better to use restart:on-failure instead like other kartoza project? https://docs.docker.com/engine/reference/run/#/restart-policies-restart

**Comment by meomancer** [comment]
@dimasciput thank you dimas
added on-failed:5

**Comment by timlinux** [comment]
LGTM

**Comment by cchristelis** [comment]
@meomancer, I think this is an OK approach, but I do think we should rather create a second uwsgi configuration in docker compose. Let's call it `uwsgi_ephemeral`. This configuration should not restart at all. We use the `uwgi_ephemeral` whenever we do a shell, migrate etc. Then the other containers could continue with reload always.

**Comment by meomancer** [comment]
@cchristelis 
i added uwsgi-ephemeral container and change makefile (migrate, shell) to access uwsgi-ephemeral except for reload

**Comment by meomancer** [comment]
Going to merge this PR and make new PR for uwsgi_ephemeral

**Pull request merged**
