### PR TITLE
Use a page object as home page instead of a static page

### LINKED ISSUE #57: Use a page object as home page instead of a static page
See in urls.py how to do this:

```
    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),
```

We should try to recreate the look of the current index page, but this will let us update the gallery and carousel programmatically.

### PR DESCRIPTION
**Pull request by dimasciput**
Fix #57 

You will need create a page name 'home' in admin with url '/' in metadata. Add images in slides section for header background. 

github-1

### CODE REVIEW

**Comment by timlinux** [comment]
Great stuff @dimasciput . Could you make some notes in the readme sot hat someone spinning up a new instance will know how to get started? Also will you make the needed start page on mezzanine.kartoza.com so we can go live with what is on there?

**Comment by dimasciput** [comment]
@timlinux Updated readme, yes I can update the mezzanine site once this branch merged.

**Comment by timlinux** [comment]
Can you update on the status of this @dimasciput ? What still needs to be done before we can merge it?

**Comment by dimasciput** [comment]
@timlinux I think it's ready to be merged

**Pull request merged**
