### PR TITLE
Fixed background images styling

### PR DESCRIPTION
**Pull request by Christiaanvdm**
This closes kartoza/kartoza.com#97

NewGIF

### CODE REVIEW

**Comment by carina1000** [comment]
Yes looks muuch better thanks @Christiaanvdm

**Comment by carina1000** [comment]
Still looking funky on our live site...When are you going to deploy these changes?

**Comment by dimasciput** [comment]
@Christiaanvdm can you try phone resolution? what it looks like

**Comment by Christiaanvdm** [comment]
Responsive results:
NewGIF

**Review by dimasciput — APPROVED** [review]

**Pull request merged**
