### PR TITLE
Update makefile

### PR DESCRIPTION
**Pull request by boney-bun**

### CODE REVIEW

**Review by timlinux — COMMENTED** [review]
One further improvement we could make is to deploy them all into the same directory since staging, testing and production will be on different hosts, we can use the same directory name e.g. /home/web/kartoza.com for all....

**Comment by boney-bun** [comment]
agreed.
what about parameterized the location (as in the new commit)?

**Review by timlinux — APPROVED** [review]
LGTM thanks

**Comment by boney-bun** [comment]
thanks @timlinux 
i'll merge it

**Pull request merged**
