### PR TITLE
added file collections plugin

### LINKED ISSUE #64: Add support for file collections
See

https://github.com/thibault/mezzanine-file-collections

This will let us host e.g. sample datasets on the web site.

### PR DESCRIPTION
**Pull request by meomancer**
this fix #64 
screenshot from 2016-09-01 12 15 52

after plugin :
screenshot from 2016-09-01 12 16 13
screenshot from 2016-09-01 12 13 17

### CODE REVIEW

**Comment by meomancer** [comment]
Updating the layout for kartoza theme for media library page

**Comment by timlinux** [comment]
Great stuff @meomancer !

**Comment by meomancer** [comment]
screenshot from 2016-09-01 14 37 44

@timlinux i think we could ask maria to make icon for each of type of file for the future, and maybe good styling?

**Comment by meomancer** [comment]
this PR is in hold
migrations for this PR is broken due to using south

**Comment by meomancer** [comment]
PR updated
change requirement using mezzanine-file-collections for django 1.8
migration is not broken now

**Comment by cchristelis** [comment]
LGTM

**Pull request merged**
