### PR TITLE
implement pdf invoices

### LINKED ISSUE #205: Kartoza course invoice PDFs
_From @christodewit on August 16, 2017 12:59_

# Problem

Customers want to (optionally) get their invoice as a pdf. Currently they get it emailed as html and have no way of retrieving it if they lose the email. (tbc). This also does not meet the requirements of many clients, especially government departments.  

The customer should also be able to go back to the shop and download their pdf any time. 

# Proposed solution

implement the pdf invoice download functionality that is already present in Cartridge

Additionally, digitally sign the invoice. 

_Copied from original issue: kartoza/kartoza#438_

### PR DESCRIPTION
**Pull request by boney-bun**
- updates the invoice layout
- updates xhtml2pdf (0.0.6 to 0.2b) and html5lib (0.9999 to 1.0b8) in REQUIREMENTS.txt

fix #205

the reason using xhtml2pdf is because the feature is already there.

the working version:
mezzanine pdf

Note: the pdf layout is not as pretty as the html version:  
mezzanine pdf-2

generated pdf sample:
[kartoza-invoice-29.pdf](https://github.com/kartoza/docker-mezzanine/files/1474257/kartoza-invoice-29.pdf)

### CODE REVIEW

**Comment by gubuntu** [comment]
good that you've got it working but it's not ready to merge. 

pdf layout really needs improvement. e.g. the sample should fit on one page. Also no Kartoza logo. 

Does the pdf get emailed to the user along with the html version?

**Comment by boney-bun** [comment]
using `xhtml2pdf`, the pdf layout much better now (although the logo still not shows up).
from the html page two links are added: 
* generate pdf.
* resend the invoice.

below is the demo:
mezzanine205

**Comment by boney-bun** [comment]
the logo shows up in pdf now.
below is the working example:
invoiceinpdf

**Comment by gubuntu** [comment]
much nicer! LGTM

**Comment by boney-bun** [comment]
thanks @gubuntu i'll merge them

**Pull request merged**
